# Generated by Django 4.0.4 on 2022-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('age', models.IntegerField(max_length=3, verbose_name='Фамилия')),
                ('achivments', models.CharField(max_length=250, verbose_name='Фамилия')),
            ],
        ),
    ]
