# Generated by Django 4.0.4 on 2022-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='achivments',
            field=models.CharField(max_length=250, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='age',
            field=models.IntegerField(max_length=3, verbose_name='Возраст'),
        ),
    ]
