# Generated by Django 4.0.4 on 2022-05-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_trainers_achivments_alter_trainers_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
