# Generated by Django 4.0.4 on 2022-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trainers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Тип')),
                ('description', models.CharField(max_length=25, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=250, verbose_name='Имя клуба')),
                ('location', models.CharField(max_length=250, verbose_name='Местонахождение')),
                ('workin_hours', models.CharField(max_length=13, verbose_name='Рабочие часы')),
                ('date', models.DateField(verbose_name='Дата открытия')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.CharField(max_length=25, verbose_name='Оборудование')),
                ('amount', models.IntegerField(max_length=6, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Тренажер',
                'verbose_name_plural': 'Тренажеры',
            },
        ),
        migrations.CreateModel(
            name='grouptraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouptraining', models.CharField(max_length=250, verbose_name='Груповая тренировка')),
                ('gr_description', models.CharField(max_length=250, verbose_name='Описание тренировки')),
                ('personal', models.CharField(max_length=50, verbose_name='Тренер')),
                ('datetime', models.DateTimeField(verbose_name='Время тренировки')),
            ],
            options={
                'verbose_name': 'Груповая тренировка',
                'verbose_name_plural': 'Груповые тренировки',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100, verbose_name='Партнер')),
                ('product', models.CharField(max_length=100, verbose_name='Товар')),
                ('contract', models.CharField(max_length=250, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
