# Generated by Django 4.0.4 on 2022-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historicalpartners_historicalgrouptraining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgrouptraining',
            name='personal',
        ),
        migrations.AlterField(
            model_name='abonements',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.RemoveField(
            model_name='grouptraining',
            name='personal',
        ),
        migrations.AddField(
            model_name='grouptraining',
            name='personal',
            field=models.ManyToManyField(to='main.trainers', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='historicalabonements',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='historicalequipments',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='historicaltrainers',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
